// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkv1ivMs12Cr3ugkG1RLxWoFVq8RsSad0',
    appId: '1:745544617763:web:9421a30d66af08ff7cc696',
    messagingSenderId: '745544617763',
    projectId: 'integra-app-8793c',
    authDomain: 'integra-app-8793c.firebaseapp.com',
    storageBucket: 'integra-app-8793c.firebasestorage.app',
    measurementId: 'G-9J32ZZV26N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX6WHMFhQdSxUOOwBsk9olOve3sIUrxcc',
    appId: '1:745544617763:android:e180c99186f5d8447cc696',
    messagingSenderId: '745544617763',
    projectId: 'integra-app-8793c',
    storageBucket: 'integra-app-8793c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0v0dYFpdEJsSkbetYaHeivzRqiEpkEsE',
    appId: '1:745544617763:ios:e356eb14622324007cc696',
    messagingSenderId: '745544617763',
    projectId: 'integra-app-8793c',
    storageBucket: 'integra-app-8793c.firebasestorage.app',
    iosBundleId: 'com.milhomes.integraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0v0dYFpdEJsSkbetYaHeivzRqiEpkEsE',
    appId: '1:745544617763:ios:e356eb14622324007cc696',
    messagingSenderId: '745544617763',
    projectId: 'integra-app-8793c',
    storageBucket: 'integra-app-8793c.firebasestorage.app',
    iosBundleId: 'com.milhomes.integraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkv1ivMs12Cr3ugkG1RLxWoFVq8RsSad0',
    appId: '1:745544617763:web:c28c448962d7ced67cc696',
    messagingSenderId: '745544617763',
    projectId: 'integra-app-8793c',
    authDomain: 'integra-app-8793c.firebaseapp.com',
    storageBucket: 'integra-app-8793c.firebasestorage.app',
    measurementId: 'G-WNBVGRBNN4',
  );

}